// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAwosCarrilloShop.Data;

namespace ProyectoAwosCarrilloShop.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20241202002042_CarritoUpdateMigracion")]
    partial class CarritoUpdateMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Carrito", b =>
                {
                    b.Property<int>("CarritoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CliID")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("CarritoID");

                    b.HasIndex("CliID")
                        .IsUnique();

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Cliente", b =>
                {
                    b.Property<int>("CliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CliCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CliDir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CliEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CliFechReg")
                        .HasColumnType("datetime2");

                    b.Property<string>("CliNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CliPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CliID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.DetalleCarrito", b =>
                {
                    b.Property<int>("CarritoID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Subtotal")
                        .HasColumnType("int");

                    b.HasKey("CarritoID", "ID");

                    b.HasIndex("ID");

                    b.ToTable("DetallesCarrito");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Carrito", b =>
                {
                    b.HasOne("ProyectoAwosCarrilloShop.Data.Models.Cliente", "Cliente")
                        .WithOne("Carrito")
                        .HasForeignKey("ProyectoAwosCarrilloShop.Data.Models.Carrito", "CliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.DetalleCarrito", b =>
                {
                    b.HasOne("ProyectoAwosCarrilloShop.Data.Models.Carrito", "Carrito")
                        .WithMany("DetallesCarrito")
                        .HasForeignKey("CarritoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAwosCarrilloShop.Data.Models.Producto", "Producto")
                        .WithMany("DetallesCarrito")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Carrito", b =>
                {
                    b.Navigation("DetallesCarrito");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Cliente", b =>
                {
                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("ProyectoAwosCarrilloShop.Data.Models.Producto", b =>
                {
                    b.Navigation("DetallesCarrito");
                });
#pragma warning restore 612, 618
        }
    }
}
